version: '4'
services:
  db:
    image: postgres:alpine
    ports:
      - 54023:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=docker
      - POSTGRES_DB=teste
  app:
    build: .
    command: npm start
    ports:
      - 5000:3000
    environment:
      - PORT=3000
      - DB_USER=docker
      - DB_PASS=1234
      - DB_NAME=teste
      - DB_DIALECT=postgres
      - DB_PORT=5432
      - HOST=172.23.0.2
    depends_on:
      - db
    links:
      - db
networks:
  default:
    name: api_net
    external: true